include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/generated/**"
    - "**/.dart_tool/**"
    - "**/build/**"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    # Freezed 3.x + Dart analyzer 7.6.0 known issue
    non_abstract_class_inherits_abstract_member: ignore

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - require_trailing_commas
    - sort_pub_dependencies
