# Build stage
FROM python:3.13-slim-bookworm AS builder
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /service

# Install build dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    make \
    curl \
    tzdata \
    libedit2 \
    libopus-dev \
    libvpx-dev \
    python3-dev \
    rustc \
    cargo \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

# Set timezone
RUN ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

# Copy only necessary files
COPY ./backend-py/app/pyproject.toml /service/pyproject.toml
COPY ./backend-py/app /service/app

ENV RUSTFLAGS="-C target-feature=-crt-static"

# Install dependencies
RUN uv cache clean
RUN uv sync --no-dev

# Production stage
FROM python:3.12-slim-bookworm

WORKDIR /service

# Copy only necessary files from builder
COPY --from=builder /service/.venv /service/.venv
COPY --from=builder /service/app /service/app

# Set timezone
RUN ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV PATH="/service/.venv/bin:$PATH"
ENV PYTHONPATH="/service/app/src:$PYTHONPATH"

# Expose port
EXPOSE 8000
EXPOSE 10000

# Set user
RUN useradd -m -s /bin/bash appuser && \
    chown -R appuser:appuser /service
USER appuser

# Command to run the application
CMD ["sh", "-c", ". .venv/bin/activate && cd app/src && uvicorn app:app --host 0.0.0.0"]
